### ISSUE TITLE
Pin elements to screen

### ISSUE THREAD

**Issue by Madis0** [jadc/headdowndisplay#2]
I wish there was a way to keep specific important elements on screen, such as the hotbar and health. The rest can hide automatically 🙂

**Comment by jadc** [comment]
How the fuck did you even find this github

**Comment by jadc** [comment]
This is out of the scope of what I wanted to do for this project. I'm unlikely to implement this. Thanks for the suggestion. :)

You can somewhat get this effect by modifying the vertical offsets in the config.
